### ISSUE TITLE
When import it says that aren't module or component of angular

### ISSUE THREAD

**Issue by Alessandroinfo** [devconcept/ng-shopping-cart#5]
#### I'm submitting a...

- [ ] Regression
- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Support request

#### Environment

Angular version: major.minor.patch 
8.0.0

NgShoppingCart version: major.minor.patch 
1.0.0

Browser: Name, Platform, Version 

Platform:  Name, Version 

Node version: major.minor.patch 
12.0.0

#### Current behavior

In a brand new project with **Angular** and added **ng-shopping-cart** with _npm_, when import it says that aren't module or component of angular
It seems that there aren't the decorator for components and module in the npm package.

I use a **SharedModule** for exporting all the modules or component necessary for other Modules/Components, and i use the _Lazy Loading_ of Modules.

In my SharedModule when i import **ShoppingCartModule** tslint says that:

> Class ShoppingCartModule is not an Angular module
![image](https://user-images.githubusercontent.com/6276276/60606967-9d4d1d80-9dbc-11e9-8414-05583a6ed6ed.png)

**Comment by devconcept** [comment]
Edit the issue and add a code sample or specify hoy I can reproduce your problem. Without that information it is not possible to know what is going on in your code.

**Comment by Alessandroinfo** [comment]
> Edit the issue and add a code sample or specify hoy I can reproduce your problem. Without that information it is not possible to know what is going on in your code.

Thank in advance for **ng-shopping-cart** i really appreciate it!
Now i update my issue with more code.

**Comment by devconcept** [comment]
You are importing the module incorrectly. You must use `forRoot` or `forChild` to remove the warning. Older versions of Angular play well with just referencing the module. It doesn't work the same way for recent Angular versions.

Check https://devconcept.github.io/ng-shopping-cart/guide/get-started#configuring for more information.

**Comment by Alessandroinfo** [comment]
> You are importing the module incorrectly. You must use `forRoot` or `forChild` to remove the warning. Older versions of Angular play well with just referencing the module. It doesn't work the same way for recent Angular versions.
> 
> Check https://devconcept.github.io/ng-shopping-cart/guide/get-started#configuring for more information.

When i import shoppingcart with **.forChild** in the **sharedModule** i get this error in the **export** field:

![image](https://user-images.githubusercontent.com/6276276/60647412-f7da8e00-9e3d-11e9-8076-afead3130600.png)
 And when i import the component in a module loaded in lazy mode i get this error:
![image](https://user-images.githubusercontent.com/6276276/60647531-3a9c6600-9e3e-11e9-9c7f-755412f60dfe.png)

and i get this error:

`ERROR Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NavbarComponent -> CartService]: StaticInjectorError(Platform: core)[NavbarComponent -> CartService]: NullInjectorError: No provider for CartService! NullInjectorError: StaticInjectorError(AppModule)[NavbarComponent -> CartService]: StaticInjectorError(Platform: core)[NavbarComponent -> CartService]: NullInjectorError: No provider for CartService! at NullInjector.get (http://localhost:5500/vendor.js:64338:27) at resolveToken (http://localhost:5500/vendor.js:64665:24) at tryResolveToken (http://localhost:5500/vendor.js:64591:16) at StaticInjector.get (http://localhost:5500/vendor.js:64454:20) at resolveToken (http://localhost:5500/vendor.js:64665:24) at tryResolveToken (http://localhost:5500/vendor.js:64591:16) at StaticInjector.get (http://localhost:5500/vendor.js:64454:20) at resolveNgModuleDep (http://localhost:5500/vendor.js:86102:29) at NgModuleRef_.get (http://localhost:5500/vendor.js:87190:16) at resolveNgModuleDep (http://localhost:5500/vendor.js:86102:29)`

**Comment by devconcept** [comment]
Do you imported it as well in the `AppModule` with the `forRoot` function?

Check the docs https://angular.io/guide/ngmodule-faq#what-is-the-forroot-method

You have to specify the type of your `MODULES` instead of let the compiler to infer it for you

`const MODULES: any[] = [`

like this

**Comment by Alessandroinfo** [comment]
Yes i've import as *forRoot()* in *AppModule* :


```
@NgModule({
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    SharedModule.forRoot(),
    ShoppingCartModule.forRoot({
      itemType: TourCartItem,
      serviceType: 'localStorage',
      serviceOptions: {storageKey: 'ToursCart', clearOnError: true},
    }),
    CoreModule
  ],
  providers: [],
  bootstrap: [CoreComponent]
})
export class AppModule {
  constructor() {
    if (!environment.production) {
      console.log('app');
    }
  }
}
```

Now i've added this like you explained:
```
const MODULES: any = [
  CommonModule,
  HttpClientModule,
  MaterialModule,
  FormsModule,
  ShoppingCartModule.forChild()
];
export class SharedModule {
  constructor() {
    if (!environment.production) {
      console.log('shared');
    }
  }

  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: [
        ApiService,
        GenericFacilityService,
        {
          provide: ErrorHandler,
          useClass: ErrorsHandlerService
        },
        {
          provide: HTTP_INTERCEPTORS,
          useClass: LoaderInterceptorService,
          multi: true // PERMIT TO USE MULTI INTERCEPTOR FOR HTTP INTERCEPTORS
        }
      ]
    };
  }
}

```
But i receive this error:

```
compiler.js:2175 Uncaught Error: Unexpected value '[object Object]' exported by the module 'SharedModule'
    at syntaxError (compiler.js:2175)
    at compiler.js:19668
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:19666)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:19569)
    at compiler.js:19651
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:19629)
    at JitCompiler._loadModules (compiler.js:25402)
    at JitCompiler._compileModuleAndComponents (compiler.js:25385)
```


Thanks in advance for your support.

**Comment by devconcept** [comment]
Why are you using `forRoot` in your own `SharedModule`? The `forRoot` and `forChild` method are used when you declare a module that **requires configuration**. This is not the case for your `SharedModule` which can be easily configured using `InjectionToken` if you ever need it.

Anyway those are errors related to your own code and not the library itself.

**Comment by Alessandroinfo** [comment]
You mean the `.forRoot()` of my `SharedModule`? I use it for heave a singleton services that are imported in the static method `forRoot`. Now i know that is a problem related to my code, can you help me to resolve the error i receive  `Unexpected value '[object Object]'...`?

**Comment by devconcept** [comment]
Sure, remove the `forRoot` method from your `SharedModule` and use the `@NgModule` metadata to declare your components and services as usual. 

Declare your services using the `providedIn` keyword. 

```
@Injectable({
  providedIn: 'root',
})
```

Check https://stackoverflow.com/a/53008692/4015449

**Comment by devconcept** [comment]
This section explains why I had to use the `forRoot` method

https://devconcept.github.io/ng-shopping-cart/guide/the-cart-service#custom-cart-service
